spring:
  datasource:
    url: jdbc:mysql://localhost:3306/emotional_analysis?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

baidu:
  api:
    access-token: 24.d341fb11b0cb89b5d8c79d96df51bd48.2592000.1750822957.282335-119024185
    sentiment-url: https://aip.baidubce.com/rpc/2.0/nlp/v1/sentiment_classify?charset=UTF-8&access_token=